### ISSUE TITLE
Model run stuck at runfile

### ISSUE THREAD

**Issue by soheile-antar** [t-wolfeadam/Alpyne#23]
Hi.
I'm trying to run the stock management model using the RLpolicy. At first the model kept running for more than 5 hours and finally gave a timeout error. Complete console output below:

-------------------------------------------
| rollout/                |               |
|    ep_len_mean          | 1             |
|    ep_rew_mean          | -1            |
| time/                   |               |
|    fps                  | 3             |
|    iterations           | 19            |
|    time_elapsed         | 10561         |
|    total_timesteps      | 38912         |
| train/                  |               |
|    approx_kl            | -2.910383e-11 |
|    clip_fraction        | 0             |
|    clip_range           | 0.2           |
|    entropy_loss         | -1.42         |
|    explained_variance   | nan           |
|    learning_rate        | 0.0003        |
|    loss                 | 0             |
|    n_updates            | 180           |
|    policy_gradient_loss | 0             |
|    std                  | 1             |
|    value_loss           | 0             |
-------------------------------------------
-------------------------------------------
| rollout/                |               |
|    ep_len_mean          | 1             |
|    ep_rew_mean          | -1            |
| time/                   |               |
|    fps                  | 3             |
|    iterations           | 20            |
|    time_elapsed         | 11120         |
|    total_timesteps      | 40960         |
| train/                  |               |
|    approx_kl            | -5.820766e-11 |
|    clip_fraction        | 0             |
|    clip_range           | 0.2           |
|    entropy_loss         | -1.42         |
|    explained_variance   | nan           |
|    learning_rate        | 0.0003        |
|    loss                 | 0             |
|    n_updates            | 190           |
|    policy_gradient_loss | 0             |
|    std                  | 1             |
|    value_loss           | 0             |
-------------------------------------------
-------------------------------------------
| rollout/                |               |
|    ep_len_mean          | 1             |
|    ep_rew_mean          | -1            |
| time/                   |               |
|    fps                  | 3             |
|    iterations           | 21            |
|    time_elapsed         | 11667         |
|    total_timesteps      | 43008         |
| train/                  |               |
|    approx_kl            | -5.820766e-11 |
|    clip_fraction        | 0             |
|    clip_range           | 0.2           |
|    entropy_loss         | -1.42         |
|    explained_variance   | nan           |
|    learning_rate        | 0.0003        |
|    loss                 | 0             |
|    n_updates            | 200           |
|    policy_gradient_loss | 0             |
|    std                  | 1             |
|    value_loss           | 0             |
-------------------------------------------
-------------------------------------------
| rollout/                |               |
|    ep_len_mean          | 1             |
|    ep_rew_mean          | -1            |
| time/                   |               |
|    fps                  | 3             |
|    iterations           | 22            |
|    time_elapsed         | 12214         |
|    total_timesteps      | 45056         |
| train/                  |               |
|    approx_kl            | -2.910383e-11 |
|    clip_fraction        | 0             |
|    clip_range           | 0.2           |
|    entropy_loss         | -1.42         |
|    explained_variance   | nan           |
|    learning_rate        | 0.0003        |
|    loss                 | 0             |
|    n_updates            | 210           |
|    policy_gradient_loss | 0             |
|    std                  | 1             |
|    value_loss           | 0             |
-------------------------------------------
-------------------------------------------
| rollout/                |               |
|    ep_len_mean          | 1             |
|    ep_rew_mean          | -1            |
| time/                   |               |
|    fps                  | 3             |
|    iterations           | 23            |
|    time_elapsed         | 12762         |
|    total_timesteps      | 47104         |
| train/                  |               |
|    approx_kl            | -5.820766e-11 |
|    clip_fraction        | 0             |
|    clip_range           | 0.2           |
|    entropy_loss         | -1.42         |
|    explained_variance   | nan           |
|    learning_rate        | 0.0003        |
|    loss                 | 0             |
|    n_updates            | 220           |
|    policy_gradient_loss | 0             |
|    std                  | 1             |
|    value_loss           | 0             |
-------------------------------------------
--------------------------------------------
| rollout/                |                |
|    ep_len_mean          | 1              |
|    ep_rew_mean          | -1             |
| time/                   |                |
|    fps                  | 3              |
|    iterations           | 24             |
|    time_elapsed         | 13317          |
|    total_timesteps      | 49152          |
| train/                  |                |
|    approx_kl            | -1.1641532e-10 |
|    clip_fraction        | 0              |
|    clip_range           | 0.2            |
|    entropy_loss         | -1.42          |
|    explained_variance   | nan            |
|    learning_rate        | 0.0003         |
|    loss                 | 0              |
|    n_updates            | 230            |
|    policy_gradient_loss | 0              |
|    std                  | 1              |
|    value_loss           | 0              |
--------------------------------------------
--------------------------------------
| rollout/                |          |
|    ep_len_mean          | 1        |
|    ep_rew_mean          | -1       |
| time/                   |          |
|    fps                  | 3        |
|    iterations           | 25       |
|    time_elapsed         | 13864    |
|    total_timesteps      | 51200    |
| train/                  |          |
|    approx_kl            | 0.0      |
|    clip_fraction        | 0        |
|    clip_range           | 0.2      |
|    entropy_loss         | -1.42    |
|    explained_variance   | nan      |
|    learning_rate        | 0.0003   |
|    loss                 | 0        |
|    n_updates            | 240      |
|    policy_gradient_loss | 0        |
|    std                  | 1        |
|    value_loss           | 0        |
--------------------------------------
-------------------------------------------
| rollout/                |               |
|    ep_len_mean          | 1             |
|    ep_rew_mean          | -1            |
| time/                   |               |
|    fps                  | 3             |
|    iterations           | 26            |
|    time_elapsed         | 14410         |
|    total_timesteps      | 53248         |
| train/                  |               |
|    approx_kl            | -2.910383e-11 |
|    clip_fraction        | 0             |
|    clip_range           | 0.2           |
|    entropy_loss         | -1.42         |
|    explained_variance   | nan           |
|    learning_rate        | 0.0003        |
|    loss                 | 0             |
|    n_updates            | 250           |
|    policy_gradient_loss | 0             |
|    std                  | 1             |
|    value_loss           | 0             |
-------------------------------------------
-------------------------------------------
| rollout/                |               |
|    ep_len_mean          | 1             |
|    ep_rew_mean          | -1            |
| time/                   |               |
|    fps                  | 3             |
|    iterations           | 27            |
|    time_elapsed         | 14955         |
|    total_timesteps      | 55296         |
| train/                  |               |
|    approx_kl            | -2.910383e-11 |
|    clip_fraction        | 0             |
|    clip_range           | 0.2           |
|    entropy_loss         | -1.42         |
|    explained_variance   | nan           |
|    learning_rate        | 0.0003        |
|    loss                 | 0             |
|    n_updates            | 260           |
|    policy_gradient_loss | 0             |
|    std                  | 1             |
|    value_loss           | 0             |
-------------------------------------------
-------------------------------------------
| rollout/                |               |
|    ep_len_mean          | 1             |
|    ep_rew_mean          | -1            |
| time/                   |               |
|    fps                  | 3             |
|    iterations           | 28            |
|    time_elapsed         | 15506         |
|    total_timesteps      | 57344         |
| train/                  |               |
|    approx_kl            | -5.820766e-11 |
|    clip_fraction        | 0             |
|    clip_range           | 0.2           |
|    entropy_loss         | -1.42         |
|    explained_variance   | nan           |
|    learning_rate        | 0.0003        |
|    loss                 | 0             |
|    n_updates            | 270           |
|    policy_gradient_loss | 0             |
|    std                  | 1             |
|    value_loss           | 0             |
-------------------------------------------
-------------------------------------------
| rollout/                |               |
|    ep_len_mean          | 1             |
|    ep_rew_mean          | -1            |
| time/                   |               |
|    fps                  | 3             |
|    iterations           | 29            |
|    time_elapsed         | 16050         |
|    total_timesteps      | 59392         |
| train/                  |               |
|    approx_kl            | -2.910383e-11 |
|    clip_fraction        | 0             |
|    clip_range           | 0.2           |
|    entropy_loss         | -1.42         |
|    explained_variance   | nan           |
|    learning_rate        | 0.0003        |
|    loss                 | 0             |
|    n_updates            | 280           |
|    policy_gradient_loss | 0             |
|    std                  | 1             |
|    value_loss           | 0             |
-------------------------------------------
-------------------------------------------
| rollout/                |               |
|    ep_len_mean          | 1             |
|    ep_rew_mean          | -1            |
| time/                   |               |
|    fps                  | 3             |
|    iterations           | 30            |
|    time_elapsed         | 16599         |
|    total_timesteps      | 61440         |
| train/                  |               |
|    approx_kl            | -5.820766e-11 |
|    clip_fraction        | 0             |
|    clip_range           | 0.2           |
|    entropy_loss         | -1.42         |
|    explained_variance   | nan           |
|    learning_rate        | 0.0003        |
|    loss                 | 0             |
|    n_updates            | 290           |
|    policy_gradient_loss | 0             |
|    std                  | 1             |
|    value_loss           | 0             |
-------------------------------------------
-------------------------------------------
| rollout/                |               |
|    ep_len_mean          | 1             |
|    ep_rew_mean          | -1            |
| time/                   |               |
|    fps                  | 3             |
|    iterations           | 31            |
|    time_elapsed         | 17152         |
|    total_timesteps      | 63488         |
| train/                  |               |
|    approx_kl            | -8.731149e-11 |
|    clip_fraction        | 0             |
|    clip_range           | 0.2           |
|    entropy_loss         | -1.42         |
|    explained_variance   | nan           |
|    learning_rate        | 0.0003        |
|    loss                 | 0             |
|    n_updates            | 300           |
|    policy_gradient_loss | 0             |
|    std                  | 1             |
|    value_loss           | 0             |
-------------------------------------------
--------------------------------------------
| rollout/                |                |
|    ep_len_mean          | 1              |
|    ep_rew_mean          | -1             |
| time/                   |                |
|    fps                  | 3              |
|    iterations           | 32             |
|    time_elapsed         | 17693          |
|    total_timesteps      | 65536          |
| train/                  |                |
|    approx_kl            | -1.1641532e-10 |
|    clip_fraction        | 0              |
|    clip_range           | 0.2            |
|    entropy_loss         | -1.42          |
|    explained_variance   | nan            |
|    learning_rate        | 0.0003         |
|    loss                 | 0              |
|    n_updates            | 310            |
|    policy_gradient_loss | 0              |
|    std                  | 1              |
|    value_loss           | 0              |
--------------------------------------------
-------------------------------------------
| rollout/                |               |
|    ep_len_mean          | 1             |
|    ep_rew_mean          | -1            |
| time/                   |               |
|    fps                  | 3             |
|    iterations           | 33            |
|    time_elapsed         | 18237         |
|    total_timesteps      | 67584         |
| train/                  |               |
|    approx_kl            | -8.731149e-11 |
|    clip_fraction        | 0             |
|    clip_range           | 0.2           |
|    entropy_loss         | -1.42         |
|    explained_variance   | nan           |
|    learning_rate        | 0.0003        |
|    loss                 | 0             |
|    n_updates            | 320           |
|    policy_gradient_loss | 0             |
|    std                  | 1             |
|    value_loss           | 0             |
-------------------------------------------
-------------------------------------------
| rollout/                |               |
|    ep_len_mean          | 1             |
|    ep_rew_mean          | -1            |
| time/                   |               |
|    fps                  | 3             |
|    iterations           | 34            |
|    time_elapsed         | 18780         |
|    total_timesteps      | 69632         |
| train/                  |               |
|    approx_kl            | -2.910383e-11 |
|    clip_fraction        | 0             |
|    clip_range           | 0.2           |
|    entropy_loss         | -1.42         |
|    explained_variance   | nan           |
|    learning_rate        | 0.0003        |
|    loss                 | 0             |
|    n_updates            | 330           |
|    policy_gradient_loss | 0             |
|    std                  | 1             |
|    value_loss           | 0             |
-------------------------------------------
-------------------------------------------
| rollout/                |               |
|    ep_len_mean          | 1             |
|    ep_rew_mean          | -1            |
| time/                   |               |
|    fps                  | 3             |
|    iterations           | 35            |
|    time_elapsed         | 19320         |
|    total_timesteps      | 71680         |
| train/                  |               |
|    approx_kl            | -8.731149e-11 |
|    clip_fraction        | 0             |
|    clip_range           | 0.2           |
|    entropy_loss         | -1.42         |
|    explained_variance   | nan           |
|    learning_rate        | 0.0003        |
|    loss                 | 0             |
|    n_updates            | 340           |
|    policy_gradient_loss | 0             |
|    std                  | 1             |
|    value_loss           | 0             |
-------------------------------------------
--------------------------------------
| rollout/                |          |
|    ep_len_mean          | 1        |
|    ep_rew_mean          | -1       |
| time/                   |          |
|    fps                  | 3        |
|    iterations           | 36       |
|    time_elapsed         | 19859    |
|    total_timesteps      | 73728    |
| train/                  |          |
|    approx_kl            | 0.0      |
|    clip_fraction        | 0        |
|    clip_range           | 0.2      |
|    entropy_loss         | -1.42    |
|    explained_variance   | nan      |
|    learning_rate        | 0.0003   |
|    loss                 | 0        |
|    n_updates            | 350      |
|    policy_gradient_loss | 0        |
|    std                  | 1        |
|    value_loss           | 0        |
--------------------------------------
-------------------------------------------
| rollout/                |               |
|    ep_len_mean          | 1             |
|    ep_rew_mean          | -1            |
| time/                   |               |
|    fps                  | 3             |
|    iterations           | 37            |
|    time_elapsed         | 20400         |
|    total_timesteps      | 75776         |
| train/                  |               |
|    approx_kl            | -8.731149e-11 |
|    clip_fraction        | 0             |
|    clip_range           | 0.2           |
|    entropy_loss         | -1.42         |
|    explained_variance   | nan           |
|    learning_rate        | 0.0003        |
|    loss                 | 0             |
|    n_updates            | 360           |
|    policy_gradient_loss | 0             |
|    std                  | 1             |
|    value_loss           | 0             |
-------------------------------------------
Traceback (most recent call last):

  File ~\anaconda3\lib\site-packages\alpyne\client\http_client.py:38 in api_request
    response = urllib.request.urlopen(request, timeout=3)

  File ~\anaconda3\lib\urllib\request.py:214 in urlopen
    return opener.open(url, data, timeout)

  File ~\anaconda3\lib\urllib\request.py:517 in open
    response = self._open(req, data)

  File ~\anaconda3\lib\urllib\request.py:534 in _open
    result = self._call_chain(self.handle_open, protocol, protocol +

  File ~\anaconda3\lib\urllib\request.py:494 in _call_chain
    result = func(*args)

  File ~\anaconda3\lib\urllib\request.py:1375 in http_open
    return self.do_open(http.client.HTTPConnection, req)

  File ~\anaconda3\lib\urllib\request.py:1350 in do_open
    r = h.getresponse()

  File ~\anaconda3\lib\http\client.py:1377 in getresponse
    response.begin()

  File ~\anaconda3\lib\http\client.py:320 in begin
    version, status, reason = self._read_status()

  File ~\anaconda3\lib\http\client.py:281 in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")

  File ~\anaconda3\lib\socket.py:704 in readinto
    return self._sock.recv_into(b)

timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File C:\alpyne models\exported\stockManageRL.py:91 in <module>
    model.learn(500000)

  File ~\anaconda3\lib\site-packages\stable_baselines3\ppo\ppo.py:310 in learn
    return super().learn(

  File ~\anaconda3\lib\site-packages\stable_baselines3\common\on_policy_algorithm.py:247 in learn
    continue_training = self.collect_rollouts(self.env, callback, self.rollout_buffer, n_rollout_steps=self.n_steps)

  File ~\anaconda3\lib\site-packages\stable_baselines3\common\on_policy_algorithm.py:175 in collect_rollouts
    new_obs, rewards, dones, infos = env.step(clipped_actions)

  File ~\anaconda3\lib\site-packages\stable_baselines3\common\vec_env\base_vec_env.py:162 in step
    return self.step_wait()

  File ~\anaconda3\lib\site-packages\stable_baselines3\common\vec_env\dummy_vec_env.py:43 in step_wait
    obs, self.buf_rews[env_idx], self.buf_dones[env_idx], self.buf_infos[env_idx] = self.envs[env_idx].step(

  File ~\anaconda3\lib\site-packages\stable_baselines3\common\monitor.py:90 in step
    observation, reward, done, info = self.env.step(action)

  File ~\anaconda3\lib\site-packages\alpyne\client\abstract.py:240 in step
    self.sim.wait_for_completion()

  File ~\anaconda3\lib\site-packages\alpyne\client\model_run.py:115 in wait_for_completion
    status, info = self.get_state()

  File ~\anaconda3\lib\site-packages\alpyne\client\model_run.py:131 in get_state
    _, _, output = self.http_client.get(endpoint)

  File ~\anaconda3\lib\site-packages\alpyne\client\http_client.py:57 in get
    return self.api_request(url, method="GET")

  File ~\anaconda3\lib\site-packages\alpyne\client\http_client.py:45 in api_request
    raise ModelError(err.errno, "timeout|model exception", "see alpyne.log", url_path)

ModelError: ModelError[path=http://127.0.0.1:51150/runs/2/progress, status=None, error=timeout|model exception, msg='see alpyne.log'] 

Then all I did was to change the stop date in the the RL experiment in AL and export the model again. Now when I run the model, it is stuck at runfile as u can see below.

![image](https://user-images.githubusercontent.com/113601868/191234862-df78e91e-3a1c-4627-be33-e0248833bd33.png)

Any idea why this would happen? Does this mean the model is running or no? and is it normal for the run to take such a long time?

Note1: im using anaconda
Note2: total python beginner

**Comment by t-wolfeadam** [comment]
As the error message mentioned, I'd need the "alpyne.log" file to have any understanding of what may have gone wrong. As for the stuck at runtime, I'm not sure what `runfile` is doing so it's hard to say :/
