### ISSUE TITLE
Server Connection

### ISSUE THREAD

**Issue by farzaneh-mahmoudi** [t-wolfeadam/Alpyne#37]
Hello wolfeadam,
I am working on the Stock Management example that you had a video about it. I ran "[rlpolicy_train.py](https://github.com/t-wolfeadam/Alpyne/blob/main/examples/Stock%20Management%20Game/rlpolicy_train.py)"  before and I got an output but I can't run it now because it can't connect to server. Could you please check the server for this code? 
and if it's not working could you introduce a solution for running the code?
Thank you

**Comment by t-wolfeadam** [comment]
FYI the "server" is a local one hosted on your machine, not a remote one. Anyway, it's likely a problem fixed in v1.0.0. Feel free to upgrade and try there and see if your issue remains (open a new issue in that case)
