### ISSUE TITLE
Importing a trained model back into Anylogic

### ISSUE THREAD

**Issue by mjhoover1** [t-wolfeadam/Alpyne#40]
Hi, I was wondering if anyone knew once a model is trained and you have the saved model in a zip file. How do you go about integrating the model back on to Anylogic. I went through the Alpyne documentation and noticed it doesn't seem to cover this information, thanks.

**Comment by mjhoover1** [comment]
Hi @tobihoernchen, sorry for the delay and thanks for your response. I actually came across this question in the discussion https://github.com/t-wolfeadam/Alpyne/discussions/25 which made me think about trying Pypeline first too. However, since the trained model needs access to the observation space of the current simulation in Anylogic. I wasn't sure how to go about passing this information to the model to make the prediction, and then passing the action back to Anylogic.

**Comment by tobihoernchen** [comment]
Well, Pypeline can execute Python-Code from Anylogic. So you can call a Python function that takes the current observation as a parameter and returns an action. I don't think that Pypeline can handle arrays, so you might be forced to create a string/json for this.

**Comment by mjhoover1** [comment]
I was wondering if you were able to implement this could you share how you did it? @tobihoernchen Actually, if anyone implemented this for the StockManagementGame model could there share how they did it? I am determining that it's harder than I expected because I can't access the RLExperiment properties from my main model, and am having trouble recreating the JSON object for the observation because of this.
