### ISSUE TITLE
Grizzly 3.0.0 error 

### ISSUE THREAD

**Issue by jacobtw2** [t-wolfeadam/Alpyne#47]
I am getting an error in my current project. When running the training I will randomly get this error. It is not very helpful because the error string is just a bunch of html code but it seems to point towards Grizzly 3.0.0. Does anyone have any idea what this might be?

    raise ModelError(err.code, err.reason, err.read(), url_path)
alpyne.data.model_error.ModelError: ModelError[path=http://127.0.0.1:54708/runs/1/progress, status=500, error=Request failed., msg=('<html><head><title>Grizzly 3.0.0</title><style></style> </head><body><div class="header">Request '
 'failed.</div><div class="body">Request failed.</div><div '
 'class="footer">Grizzly 3.0.0</div></body></html>')]

**Comment by t-wolfeadam** [comment]
Closing as this is likely resolved in v1.0.0. Feel free to create a new issue if it remains.
