### ISSUE TITLE
"AssertionError: Unhandled type conversion" on sim.reset

### ISSUE THREAD

**Issue by t-wolfeadam** [t-wolfeadam/Alpyne#51]
When initializing the simulation with sim.reset(initialWorker=initialWorker) where initialWorker is a list of lists (e.g., initialWorker = [[1,1,0], [0,1,0], [1,0,1], [1,0,0], [1,0,1], [0,0,1]]), I receive an AssertionError: Unhandled type conversion. This setup worked seamlessly in version 0.2.0, suggesting a regression or change in how list of lists are handled.
The simulation expects an int[][] type for the corresponding variable, which matches Python's list[int[]] structure. This mismatch seems to trigger the error.
Could you provide any guidance on how to address this issue? Are there any workarounds or adjustments I can make in my code to accommodate the changes in version 1.0.0? Additionally, if there's any more information or specific error logs that would help diagnose this issue, I'm happy to provide them.
Thank you for your assistance and for the continued development of Alpyne.

_Originally posted by @HerbertRolf in https://github.com/t-wolfeadam/Alpyne/discussions/48#discussioncomment-8827782_

**Comment by t-wolfeadam** [comment]
I recreated the issue in model with the configuration having a field called "initialWorker" set to type `int[][]` and exporting it. Then using the following code:

```python
from alpyne.env import AnyLogicSim
sim = AnyLogicSim("Model353.zip")
sim.reset(initialWorker=[[1,2,3],[4,5,6],[7,8,9]])
```

Which causes the following error:

```
Traceback (most recent call last):
  File "<pyshell#5>", line 1, in <module>
    sim.reset(initialWorkers=[[1,2,3],[4,5,6],[7,8,9]])
  File "C:\Users\twolf\AppData\Roaming\Python\Python310\site-packages\alpyne\sim.py", line 349, in reset
    _config = SimConfiguration()
  File "C:\Users\twolf\AppData\Roaming\Python\Python310\site-packages\alpyne\data.py", line 32, in __init__
    self[key] = self.__missing__(key)
  File "C:\Users\twolf\AppData\Roaming\Python\Python310\site-packages\alpyne\data.py", line 51, in __missing__
    return subschema[key].py_value
  File "C:\Users\twolf\AppData\Roaming\Python\Python310\site-packages\alpyne\data.py", line 235, in py_value
    assert isinstance(self.value, self.py_type), "Unhandled type conversion"
AssertionError: Unhandled type conversion
```

Printing out the configuration schema shows the name is correct, so that's not the issue:

```python
>>> print(sim.schema.configuration)
{'initialWorker': FieldData(name='initialWorker', type='int[][]', value=None, units=None)}
```

Based on the traceback, it's building an empty `SimConfiguration` object, filling in with the default value (None) which is causing a conflict with the intended `py_type` (list).

This is a bug, as the check should either ignore for None value or bypass the assertion when creating the default object (as the user filled value will cause it to be correct) - I haven't decided yet what to do. 

Anyway, the workaround for now is to always ensure you supply some default value of the correct type in the constructor, like so:

```python
sim = AnyLogicSim("Model353.zip", config_defaults=dict(initialWorker=[]))
```

This works because it overrides the "default" value initially assigned from AnyLogic (None) to an empty list. Note that the assertion only checks for outer type (i.e., it just cares that it's a list; it doesn't look "inside" to make sure the int type is also correct)

**Comment by HerbertRolf** [comment]
Thank you! Now it works perfectly.

**Comment by t-wolfeadam** [comment]
Fixed in the latest version

**Comment by t-wolfeadam** [comment]
I deferred the error to the sim-side which will throw a non-halting error, failing when a value is null and it shouldn't be, which will be reported to Python.

You will still need to set defaults in the AnyLogicSim constructor or handle for null in the RL Experiment's Configuration
