### ISSUE TITLE
ValueError: mutable default <class 'alpyne.outputs._Statistics'> for field statistics is not allowed: use default_factory

### ISSUE THREAD

**Issue by aa6666666666990** [t-wolfeadam/Alpyne#54]
### Problematic Behavior
Hi!
Using the latest Alpyne, there is a problem running the StockManagementGame example. I'm guessing that there's a problem with this code in the src.zip where the image is displayed.

### Models + Scripts used
[src.zip](https://github.com/t-wolfeadam/Alpyne/files/15249549/src.zip)

### Log files
[console.zip](https://github.com/t-wolfeadam/Alpyne/files/15249575/console.zip)

### Environment

```markdown
- OS: Windows 11
- Python: 3.11
- Environment: 
AnyLogic: 8.8.6
```

**Comment by t-wolfeadam** [comment]
It would appear that this is a change from Python 3.11 ([python.org docs](https://docs.python.org/3/whatsnew/3.11.html#dataclasses)) and my tests were using 3.10. I'll make a note to include the relevant change in the next bug fixes, thanks!

**Comment by aa6666666666990** [comment]
It works, thanks!

**Comment by aa6666666666990** [comment]
This problem occurs when I run my model: 
alpyne.errors.ModelError: ModelError[path=, status=The underlying application failed to start. Check the logs., error=None, msg=''].
And all log files are empty. I use gis in my anylogic model, could this be the cause? Looking forward to your reply.

**Comment by xiaobo125** [comment]
I also encountered the same problem, reference instance ActivityBasedCostingAnalysis and BorderCheckpointOptimization problems like you, do you solved? Pathfinder and StockManagementGame can run normally, I build the model also appeared alpyne errors. The ModelError: ModelError[path=, status=The underlying application failed to start. Check the logs., error=None, msg= "], some on different computers can succeed. For some reason, the exported model zip file does not delete lib can solve this problem, but only partially, now I still can not run my model,

**Comment by t-wolfeadam** [comment]
Apologies for the delay, but but it seems this issue is separate from the current one. Assuming it's still relevant, please post a new issue and attach both log files and the source/scripts if you can too.

**Comment by bhushan318** [comment]
Was getting same error, but got resolved using 
in alpyne\outputs.py
class HistogramSmartData(_AnalysisObject):
    count: int = 0
    lowerBound: float = 0.0
    intervalWidth: float = 0.1
    hits: list[int] = field(default_factory=list)
    statistics: _Statistics = field(default_factory=_Statistics) # new line
