### ISSUE TITLE
Connection error with Custom Environment

### ISSUE THREAD

**Issue by achrefjaziri** [t-wolfeadam/Alpyne#55]
### Problematic Behavior

I am trying to load my own custom anylogic zip file using the following command: 

```
sim = AnyLogicSim(
            r".../PlatooningRL/ModelExported/Platooning.zip",py_log_level=True,java_log_level=True,
    engine_overrides = dict(id=1)
    ) 
```

But I am getting this error. I am able to run the examples that you provided with Alpyne but I am failing to load my zip file. The log file is sadly not very telling what the error is. I included also the zip and the .alp file to replicate the error. I am using anylogic 8.9.0 and the newest version of Alpyne.  

```
url: /version (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72a900fd2cb0>: Failed to establish a new connection: [Errno 111] Connection refused'))



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/skuggig/Desktop/anylogic_exps/platooningRL/main.py", line 500, in <module>
    sim = AnyLogicSim(
  File "/home/skuggig/Desktop/anylogic_exps/platooningRL/main.py", line 135, in __init__
    self._session.get(f"{self._base_url}/version").json()
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 557, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 544, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 657, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=54065): Max retries exceeded with url: /version (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72a900fd2cb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-06-11 10:19:11,505 [__main__ @ 312][   ERROR] ALERT! All attempts to kill process with ID 659529 failed! May requires system restart or manual quit to close.

```
 
### Models + Scripts used

This is the link for the zip File for the RL experiment: https://drive.google.com/file/d/1y8Puc2KfioJFrvvcWDs2t1w6j9FhdGKG/view?usp=share_link

This is the link for the Anylogic simulation directly. You can use it to generate the zip file: 
https://drive.google.com/file/d/14ELIBMlpEcxKdeXvmU7iR3r4qDqU_eIe/view?usp=sharing

### Log files

[alpyne.log](https://github.com/user-attachments/files/15784725/alpyne.log)

### Environment

```markdown
- OS: Ubuntu 20.4
- Python: Python 3.10
- Anylogic Version: 8.9.0
```

**Comment by t-wolfeadam** [comment]
Thanks for all the info/details, it really helped with verifying the model itself wasn't the issue. 

When I tried running this, I got something similar. The model.log file had the following error:

> Exception in thread "main" java.lang.UnsupportedClassVersionError: com/anylogic/engine/ReinforcementLearningModel has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0

Turns out it's because my system using java 11 whereas the one that comes with anylogic (as of 8.9) is java 17. Check your model.log file to see if this is the same one. If it is, for now you'll need to install at least java 17 and update your system path accordingly. I'll make a note to add an option to specify the java executable.

And if it's not the same error, please attach your model.log and I'll reopen and go from there!

**Comment by achrefjaziri** [comment]
Thank you for the quick response and help. I am using Java 17 and when I run the Pathfinder example for instance, I am able to load the model and run the code. I attached the model.log file but it does not contain much information about the error. 

[model.log](https://github.com/user-attachments/files/15816704/model.log)

**Comment by t-wolfeadam** [comment]
> I am using Java 17 and when I run the Pathfinder example for instance, I am able to load the model and run the code. I attached the model.log file but it does not contain much information about the error.
> 
> [model.log](https://github.com/user-attachments/files/15816704/model.log)

FYI the text in that log is from your model's `initVariablesRL` function in the line `System.out.println(nodes_name);`. Primitive arrays just output their data type + memory address to the console, so you'll need to wrap it in some other function to serialize it correctly (e.g., `Arrays.toString(nodes_name)`).

As for the actual issue, previously I could run your model without issue (after fixing the java issue). Today, I reran it and it encountered the error you're describing, increased the verbosity (to `logging.DEBUG`), then it worked. But even after switching it back, it worked again, and now I can't recreate it.

To verify it can load correctly for you, try launching the server manually. This can be done using [this script](https://gist.github.com/t-wolfeadam/5a5b17bb52c574cfccbf159d42eda405) (instructions at the top).

**Comment by achrefjaziri** [comment]
Thank you for help. I was able to launch it manually and I was able to get the Auto-generated endpoint documentation. 

I also managed to solve the issue by adding time.sleep(10) after self._start_app(...) in AnyLogicSim Class.  Thank you for you help. I will close the issue for now.
