### ISSUE TITLE
Simulation hangs when creating the "client"

### ISSUE THREAD

**Issue by negodfre** [t-wolfeadam/Alpyne#6]
Hello,

I was testing Alpyne with a different simulation.
However, I never get an error message & the simulation just hangs (see log below).

When the simulation never starts (never get past creating the 'client'), is there a way to identify what the problem might be?

**Code:**
if __name__ == "__main__":

    `print("Creating` client")
    client = AlpyneClient(r"Exported1\model.jar", blocking=True, verbose=True)
    print("Client finished creating...")

    print("\nClient Config Temp: ", client.configuration_template)
    print("\nClient Obs Temp: ", client.observation_template)
    print("\nClient Action Temp: ", client.action_template)
    print("\nClient Out Temp: ", client.output_names)
    print("\nClient Methods", dir(client))

    config = client.create_default_rl_inputs()  # == configuration_template

    config.engine_seed = 1 # fixed seed

    sim = client.create_reinforcement_learning(config)\
                .run()

    print("\nSim Methods: ", dir(sim))

    while not sim.is_terminal():
        status, info = sim.last_state  # updated when status is polled (automatically done thx to `blocking=True`)
        print(f"Current sim status/info = {status} | {info}")

        observation = sim.get_observation()
        print(f"Observation = {observation}", end="\n\n")

        # query order rate based on function chosen
        action = client.action_template
        action.next_var = 0
        sim.take_action(action)

    print(f"Finished! Final state = {sim.last_state}.")
    print(f"Final observation = {sim.get_observation()}")

    outputs = sim.get_outputs()`

**Log:**
```
[2021-11-22 11:56:22] INFO    @ com.anylogic.alpyne.AlpyneServer main 
                              | [PID=24648] Initializing @ 'C:\Users\test_user\Models\test_example\Exported1' with arguments: {path=., port=51150, dev_mode=false}
[2021-11-22 11:56:22] FINER   @ ModelManager.<init>
                              | ENTRY {0}	.
[2021-11-22 11:56:22] FINER   @ BonsaiBrainLearningPlatform.<init>
                              | ENTRY {0}	{}
[2021-11-22 11:56:22] INFO    @ Version.load
                              | Loading from experiment
[2021-11-22 11:56:30] INFO    @ Version.load
                              | Inputs      = [(BOOLEAN)x_one=null, (BOOLEAN)x_two=null, (BOOLEAN)x_three=null, (BOOLEAN)x_four=null, (BOOLEAN)x_five=null, (BOOLEAN)x_six=null, (BOOLEAN)x_seven=null, (BOOLEAN)x_eight=null, (BOOLEAN)inRLMode=null, (DOUBLE){START_TIME}=0.0, (DATE_TIME){START_DATE}=Tue Dec 31 22:00:00 EST 2019, (DOUBLE){STOP_TIME}=336.0833333333333, (DATE_TIME){STOP_DATE}=Wed Dec 02 00:00:00 EST 2020, (LONG){RANDOM_SEED}=null]
                                Outputs     = [(DOUBLE)rewardOut=null]
                                Config      = [(INTEGER)cfg_var_one=null, (INTEGER)cfg_var_two=null, (INTEGER)cfg_var_three=null, (INTEGER)cfg_var_four=null, (INTEGER)cfg_var_five=null, (INTEGER)cfg_var_six=null, (INTEGER)cfg_var_seven=null, (INTEGER)cfg_var_eight=null, (DOUBLE){START_TIME}=0.0, (DATE_TIME){START_DATE}=Tue Dec 31 22:00:00 EST 2019, (DOUBLE){STOP_TIME}=336.0833333333333, (DATE_TIME){STOP_DATE}=Wed Dec 02 00:00:00 EST 2020, (LONG){RANDOM_SEED}=null]
                                Observation = [(DOUBLE_ARRAY)varOne=null, (DOUBLE_ARRAY)varTwo=null, (DOUBLE)varThree=null]
                                Action      = [(INTEGER)next_var=null]
[2021-11-22 11:56:30] WARNING @ org.glassfish.jersey.server.wadl.WadlFeature configure 
                              | JAX-B API not found . WADL feature is disabled.
[2021-11-22 11:56:31] INFO    @ org.glassfish.grizzly.http.server.NetworkListener start 
                              | Started listener bound to [localhost:51150]
[2021-11-22 11:56:31] INFO    @ org.glassfish.grizzly.http.server.HttpServer start 
                              | [HttpServer] Started.
```

**Comment by negodfre** [comment]
I think I may have found the issue.
I am not entirely sure why, but it seems to hang every time I checkbox "Log Model Execution" in "Database" object within AnyLogic.

**Comment by negodfre** [comment]
I think I may have found the issue.
I am not entirely sure why, but it seems to hang every time I checkbox "Log Model Execution" in "Database" object within AnyLogic.

**Comment by t-wolfeadam** [comment]
@negodfre Hm...without seeing the model it's hard to say why specifically this happened. If you're able to share that, it would be really valuable. 

Otherwise, my only suggestion in the future would be to - assuming you're using an IDE - try creating a breakpoint stepping through the creation of the client to see where exactly it hangs. In the past I've had issue with urllib's timeout working as expected and this may be related.

**Comment by negodfre** [comment]
Unfortunately, I cannot share that model.
However, I did test out the 'fix' / 'break' on the "Stock Management Game" and achieved the same results.
When the "Log model execution" checkbox is selected within the Database, the "simple run - single.py" will 'hang'.

**Comment by KevinChngJY** [comment]
I'm running the sample script - Dummy Process, i have double confirmed that the checkbox of db is not checked. However, my running is also hang. I'm not really sure why.....

**Comment by t-wolfeadam** [comment]
@negodfre Thanks for checking with the other example model! I'll look into that
