### ISSUE TITLE
Java not found. Please check your system path

### ISSUE THREAD

**Issue by KevinChngJY** [t-wolfeadam/Alpyne#8]
raise RuntimeError("Java not found. Please check your system path.")
RuntimeError: Java not found. Please check your system path.

----------------------------------------------------------------------
Ran 6 tests in 1.539s

Any solution for the above error?

**Comment by KevinChngJY** [comment]
alpyne.data.model_error.ModelError: ModelError[path=, status=Failed to properly start the app. Error from process: Error: A JNI error has occurred, please check your installation and try again
, error=None, msg='']

After setting the environment path for java jre1.8.0_311, i got a new error.

**Comment by KevinChngJY** [comment]
Issue is addressed for jre1.8.0_311

**Comment by t-wolfeadam** [comment]
Glad you found a solution, but FYI, Java 11 (OpenJDK) is the minimum recommended version. It will likely work with jre1.8 but you may also run into some issues down the line - just something to keep in mind

**Comment by KevinChngJY** [comment]
Thanks for your clarification. Eventually, I get Java 17 for my system.
